In [1]:
import pandas as pd

file_path = "../data/050625_LoL_champion_data.csv"
champion_data = pd.read_csv(file_path, index_col=0)

In [2]:
champion_data.head()

,id,apiname,title,difficulty,herotype,alttype,resource,stats,rangetype,date,...,be,rp,skill_i,skill_q,skill_w,skill_e,skill_r,skills,fullname,nickname
Aatrox,266.0,Aatrox,the Darkin Blade,2,Fighter,Tank,Blood Well,"{'hp_base': 650, 'hp_lvl': 114, 'mp_base': 0, ...",Melee,2013-06-13,...,2400,880,{1: 'Deathbringer Stance'},"{1: 'The Darkin Blade', 2: 'The Darkin Blade 3'}",{1: 'Infernal Chains'},{1: 'Umbral Dash'},{1: 'World Ender'},"{1: 'Deathbringer Stance', 2: 'The Darkin Blad...",NaN,NaN
Ahri,103.0,Ahri,the Nine-Tailed Fox,2,Mage,Assassin,Mana,"{'hp_base': 590, 'hp_lvl': 104, 'mp_base': 418...",Ranged,2011-12-14,...,1575,790,{1: 'Essence Theft'},{1: 'Orb of Deception'},{1: 'Fox-Fire'},{1: 'Charm'},{1: 'Spirit Rush'},"{1: 'Essence Theft', 2: 'Orb of Deception', 3:...",NaN,NaN
Akali,84.0,Akali,the Rogue Assassin,2,Assassin,NaN,Energy,"{'hp_base': 600, 'hp_lvl': 119, 'mp_base': 200...",Melee,2010-05-11,...,1575,790,"{1: ""Assassin's Mark""}",{1: 'Five Point Strike'},{1: 'Twilight Shroud'},{1: 'Shuriken Flip'},{1: 'Perfect Execution'},"{1: ""Assassin's Mark"", 2: 'Five Point Strike',...",Akali Jhomen Tethi,NaN
Akshan,166.0,Akshan,the Rogue Sentinel,3,Marksman,Assassin,Mana,"{'hp_base': 630, 'hp_lvl': 107, 'mp_base': 350...",Ranged,2021-07-22,...,2400,880,{1: 'Dirty Fighting'},{1: 'Avengerang'},{1: 'Going Rogue'},{1: 'Heroic Swing'},{1: 'Comeuppance'},"{1: 'Dirty Fighting', 2: 'Avengerang', 3: 'Goi...",NaN,NaN
Alistar,12.0,Alistar,the Minotaur,1,Tank,Support,Mana,"{'hp_base': 685, 'hp_lvl': 120, 'mp_base': 350...",Melee,2009-02-21,...,675,585,{1: 'Triumphant Roar'},{1: 'Pulverize'},{1: 'Headbutt'},{1: 'Trample'},{1: 'Unbreakable Will'},"{1: 'Triumphant Roar', 2: 'Pulverize', 3: 'Hea...",NaN,NaN

In [3]:
champion_data.columns.to_list

<bound method IndexOpsMixin.tolist of Index(['id', 'apiname', 'title', 'difficulty', 'herotype', 'alttype',
       'resource', 'stats', 'rangetype', 'date', 'patch', 'changes', 'role',
       'client_positions', 'external_positions', 'damage', 'toughness',
       'control', 'mobility', 'utility', 'style', 'adaptivetype', 'be', 'rp',
       'skill_i', 'skill_q', 'skill_w', 'skill_e', 'skill_r', 'skills',
       'fullname', 'nickname'],
      dtype='object')>

In [4]:
champion_data.dtypes

id                    float64
apiname                object
title                  object
difficulty              int64
herotype               object
alttype                object
resource               object
stats                  object
rangetype              object
date                   object
patch                  object
changes                object
role                   object
client_positions       object
external_positions     object
damage                  int64
toughness               int64
control                 int64
mobility                int64
utility                 int64
style                   int64
adaptivetype           object
be                      int64
rp                      int64
skill_i                object
skill_q                object
skill_w                object
skill_e                object
skill_r                object
skills                 object
fullname               object
nickname               object
dtype: object

In [5]:
champion_data['stats'].iloc[0]

"{'hp_base': 650, 'hp_lvl': 114, 'mp_base': 0, 'mp_lvl': 0, 'arm_base': 38, 'arm_lvl': 4.8, 'mr_base': 32, 'mr_lvl': 2.05, 'hp5_base': 3, 'hp5_lvl': 0.5, 'mp5_base': 0, 'mp5_lvl': 0, 'dam_base': 60, 'dam_lvl': 5, 'as_base': 0.651, 'as_lvl': 2.5, 'range': 175, 'ms': 345, 'acquisition_radius': 475, 'selection_height': 180, 'selection_radius': 135, 'pathing_radius': 35, 'as_ratio': 0.651000022888183, 'attack_cast_time': 0.300000011920928, 'attack_total_time': 1.51999998092651, 'aram': {'dmg_dealt': 1.05, 'dmg_taken': 1}, 'urf': {'dmg_dealt': 1.15, 'dmg_taken': 0.7}}"

In [6]:
champion_data['herotype'].value_counts()

herotype
Fighter     49
Mage        37
Marksman    28
Tank        24
Assassin    17
Support     17
Name: count, dtype: int64

In [7]:
champion_data['alttype'].value_counts()

alttype
Mage        38
Assassin    31
Support     28
Tank        25
Fighter     17
Marksman     5
Name: count, dtype: int64

In [8]:
champion_data['rangetype'].value_counts()

rangetype
Melee     91
Ranged    81
Name: count, dtype: int64

In [9]:
champion_data['difficulty'].value_counts()

difficulty
2    92
1    51
3    29
Name: count, dtype: int64

In [10]:
champion_data['adaptivetype'].value_counts()

adaptivetype
Physical    93
Magic       79
Name: count, dtype: int64

In [11]:
champion_data['role'].value_counts()

role
{'Marksman'}                  21
{'Vanguard'}                  15
{'Diver'}                     15
{'Specialist'}                14
{'Juggernaut'}                14
{'Skirmisher'}                14
{'Assassin'}                  13
{'Battlemage'}                11
{'Burst'}                     11
{'Enchanter'}                  8
{'Catcher'}                    7
{'Artillery'}                  6
{'Warden'}                     5
{'Enchanter', 'Burst'}         2
{'Assassin', 'Diver'}          2
{'Marksman', 'Assassin'}       1
{'Assassin', 'Burst'}          1
{'Skirmisher', 'Diver'}        1
{'Marksman', 'Catcher'}        1
{'Skirmisher', 'Warden'}       1
{'Artillery', 'Burst'}         1
{'Catcher', 'Burst'}           1
{'Assassin', 'Catcher'}        1
{'Marksman', 'Enchanter'}      1
{'Vanguard', 'Juggernaut'}     1
{'Skirmisher', 'Burst'}        1
{'Warden', 'Enchanter'}        1
{'Marksman', 'Artillery'}      1
{'Skirmisher', 'Assassin'}     1
Name: count, dtype: int64

In [12]:
champion_data.isnull().sum()

id                      0
apiname                 0
title                   0
difficulty              0
herotype                0
alttype                28
resource                5
stats                   0
rangetype               0
date                    0
patch                   0
changes                 0
role                    0
client_positions        0
external_positions      0
damage                  0
toughness               0
control                 0
mobility                0
utility                 0
style                   0
adaptivetype            0
be                      0
rp                      0
skill_i                 0
skill_q                 0
skill_w                 0
skill_e                 0
skill_r                 0
skills                  2
fullname              115
nickname              158
dtype: int64

In [13]:
champion_data[['herotype', 'alttype', 'rangetype', 'difficulty', 'adaptivetype', 'role', 'stats']].isnull().sum()

herotype         0
alttype         28
rangetype        0
difficulty       0
adaptivetype     0
role             0
stats            0
dtype: int64

In [14]:
champion_data.describe()

,id,difficulty,damage,toughness,control,mobility,utility,style,be,rp
count,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000,172.000000
mean,195.728488,1.872093,2.465116,1.616279,1.994186,1.790698,1.453488,59.686047,1568.906977,707.296512
std,243.326685,0.671848,0.695813,0.759634,0.721411,0.781605,0.669415,32.094437,842.690430,218.351986
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,225.000000,260.000000
25%,43.750000,1.000000,2.000000,1.000000,1.000000,1.000000,1.000000,30.000000,675.000000,585.000000
50%,102.500000,2.000000,3.000000,1.000000,2.000000,2.000000,1.000000,65.000000,1575.000000,790.000000
75%,233.250000,2.000000,3.000000,2.000000,3.000000,2.000000,2.000000,90.000000,2400.000000,880.000000
max,950.000000,3.000000,3.000000,3.000000,3.000000,3.000000,3.000000,100.000000,3150.000000,975.000000